platform :ios, '8.0'

target 'LeeLockView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'LockView', :path => '../'

  # Pods for LeeLockView

  target 'LeeLockViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeeLockViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
